CodeGeneratorRequest {
    file_to_generate: [
        "spike.proto",
    ],
    parameter: None,
    proto_file: [
        FileDescriptorProto {
            name: Some(
                "spike.proto",
            ),
            package: None,
            dependency: [],
            public_dependency: [],
            weak_dependency: [],
            message_type: [
                DescriptorProto {
                    name: Some(
                        "SubMessage",
                    ),
                    field: [],
                    extension: [],
                    nested_type: [],
                    enum_type: [],
                    extension_range: [],
                    oneof_decl: [],
                    options: MessageField(
                        None,
                    ),
                    reserved_range: [],
                    reserved_name: [],
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: None,
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
                DescriptorProto {
                    name: Some(
                        "SampleMessage",
                    ),
                    field: [
                        FieldDescriptorProto {
                            name: Some(
                                "name",
                            ),
                            number: Some(
                                4,
                            ),
                            label: Some(
                                LABEL_OPTIONAL,
                            ),
                            type_: Some(
                                TYPE_STRING,
                            ),
                            type_name: None,
                            extendee: None,
                            default_value: None,
                            oneof_index: Some(
                                0,
                            ),
                            json_name: Some(
                                "name",
                            ),
                            options: MessageField(
                                None,
                            ),
                            proto3_optional: None,
                            special_fields: SpecialFields {
                                unknown_fields: UnknownFields {
                                    fields: None,
                                },
                                cached_size: CachedSize {
                                    size: 0,
                                },
                            },
                        },
                        FieldDescriptorProto {
                            name: Some(
                                "sub_message",
                            ),
                            number: Some(
                                9,
                            ),
                            label: Some(
                                LABEL_OPTIONAL,
                            ),
                            type_: Some(
                                TYPE_MESSAGE,
                            ),
                            type_name: Some(
                                ".SubMessage",
                            ),
                            extendee: None,
                            default_value: None,
                            oneof_index: Some(
                                0,
                            ),
                            json_name: Some(
                                "subMessage",
                            ),
                            options: MessageField(
                                None,
                            ),
                            proto3_optional: None,
                            special_fields: SpecialFields {
                                unknown_fields: UnknownFields {
                                    fields: None,
                                },
                                cached_size: CachedSize {
                                    size: 0,
                                },
                            },
                        },
                    ],
                    extension: [],
                    nested_type: [],
                    enum_type: [],
                    extension_range: [],
                    oneof_decl: [
                        OneofDescriptorProto {
                            name: Some(
                                "test_oneof",
                            ),
                            options: MessageField(
                                None,
                            ),
                            special_fields: SpecialFields {
                                unknown_fields: UnknownFields {
                                    fields: None,
                                },
                                cached_size: CachedSize {
                                    size: 0,
                                },
                            },
                        },
                    ],
                    options: MessageField(
                        None,
                    ),
                    reserved_range: [],
                    reserved_name: [],
                    special_fields: SpecialFields {
                        unknown_fields: UnknownFields {
                            fields: None,
                        },
                        cached_size: CachedSize {
                            size: 0,
                        },
                    },
                },
            ],
            enum_type: [],
            service: [],
            extension: [],
            options: MessageField(
                None,
            ),
            source_code_info: MessageField(
                Some(
                    SourceCodeInfo {
                        location: [
                            Location {
                                path: [],
                                span: [
                                    0,
                                    0,
                                    9,
                                    1,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    0,
                                ],
                                span: [
                                    0,
                                    0,
                                    20,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    0,
                                    1,
                                ],
                                span: [
                                    0,
                                    8,
                                    18,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                ],
                                span: [
                                    2,
                                    0,
                                    9,
                                    1,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    1,
                                ],
                                span: [
                                    2,
                                    8,
                                    21,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    8,
                                    0,
                                ],
                                span: [
                                    4,
                                    2,
                                    8,
                                    3,
                                ],
                                leading_comments: Some(
                                    " oneof comments \n",
                                ),
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    8,
                                    0,
                                    1,
                                ],
                                span: [
                                    4,
                                    8,
                                    18,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    0,
                                ],
                                span: [
                                    6,
                                    4,
                                    20,
                                ],
                                leading_comments: Some(
                                    " field oneof comments \n",
                                ),
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    0,
                                    5,
                                ],
                                span: [
                                    6,
                                    4,
                                    10,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    0,
                                    1,
                                ],
                                span: [
                                    6,
                                    11,
                                    15,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    0,
                                    3,
                                ],
                                span: [
                                    6,
                                    18,
                                    19,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    1,
                                ],
                                span: [
                                    7,
                                    4,
                                    31,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    1,
                                    6,
                                ],
                                span: [
                                    7,
                                    4,
                                    14,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    1,
                                    1,
                                ],
                                span: [
                                    7,
                                    15,
                                    26,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                            Location {
                                path: [
                                    4,
                                    1,
                                    2,
                                    1,
                                    3,
                                ],
                                span: [
                                    7,
                                    29,
                                    30,
                                ],
                                leading_comments: None,
                                trailing_comments: None,
                                leading_detached_comments: [],
                                special_fields: SpecialFields {
                                    unknown_fields: UnknownFields {
                                        fields: None,
                                    },
                                    cached_size: CachedSize {
                                        size: 0,
                                    },
                                },
                            },
                        ],
                        special_fields: SpecialFields {
                            unknown_fields: UnknownFields {
                                fields: None,
                            },
                            cached_size: CachedSize {
                                size: 0,
                            },
                        },
                    },
                ),
            ),
            syntax: None,
            special_fields: SpecialFields {
                unknown_fields: UnknownFields {
                    fields: None,
                },
                cached_size: CachedSize {
                    size: 0,
                },
            },
        },
    ],
    compiler_version: MessageField(
        Some(
            Version {
                major: Some(
                    4,
                ),
                minor: Some(
                    25,
                ),
                patch: Some(
                    1,
                ),
                suffix: Some(
                    "",
                ),
                special_fields: SpecialFields {
                    unknown_fields: UnknownFields {
                        fields: None,
                    },
                    cached_size: CachedSize {
                        size: 0,
                    },
                },
            },
        ),
    ),
    special_fields: SpecialFields {
        unknown_fields: UnknownFields {
            fields: Some(
                {
                    17: UnknownValues {
                        fixed32: [],
                        fixed64: [],
                        varint: [],
                        length_delimited: [
                            [
                                10,
                                11,
                                115,
                                112,
                                105,
                                107,
                                101,
                                46,
                                112,
                                114,
                                111,
                                116,
                                111,
                                34,
                                12,
                                10,
                                10,
                                83,
                                117,
                                98,
                                77,
                                101,
                                115,
                                115,
                                97,
                                103,
                                101,
                                34,
                                99,
                                10,
                                13,
                                83,
                                97,
                                109,
                                112,
                                108,
                                101,
                                77,
                                101,
                                115,
                                115,
                                97,
                                103,
                                101,
                                18,
                                20,
                                10,
                                4,
                                110,
                                97,
                                109,
                                101,
                                24,
                                4,
                                32,
                                1,
                                40,
                                9,
                                72,
                                0,
                                82,
                                4,
                                110,
                                97,
                                109,
                                101,
                                18,
                                46,
                                10,
                                11,
                                115,
                                117,
                                98,
                                95,
                                109,
                                101,
                                115,
                                115,
                                97,
                                103,
                                101,
                                24,
                                9,
                                32,
                                1,
                                40,
                                11,
                                50,
                                11,
                                46,
                                83,
                                117,
                                98,
                                77,
                                101,
                                115,
                                115,
                                97,
                                103,
                                101,
                                72,
                                0,
                                82,
                                10,
                                115,
                                117,
                                98,
                                77,
                                101,
                                115,
                                115,
                                97,
                                103,
                                101,
                                66,
                                12,
                                10,
                                10,
                                116,
                                101,
                                115,
                                116,
                                95,
                                111,
                                110,
                                101,
                                111,
                                102,
                                74,
                                237,
                                1,
                                10,
                                6,
                                18,
                                4,
                                0,
                                0,
                                9,
                                1,
                                10,
                                9,
                                10,
                                2,
                                4,
                                0,
                                18,
                                3,
                                0,
                                0,
                                20,
                                10,
                                10,
                                10,
                                3,
                                4,
                                0,
                                1,
                                18,
                                3,
                                0,
                                8,
                                18,
                                10,
                                10,
                                10,
                                2,
                                4,
                                1,
                                18,
                                4,
                                2,
                                0,
                                9,
                                1,
                                10,
                                10,
                                10,
                                3,
                                4,
                                1,
                                1,
                                18,
                                3,
                                2,
                                8,
                                21,
                                10,
                                31,
                                10,
                                4,
                                4,
                                1,
                                8,
                                0,
                                18,
                                4,
                                4,
                                2,
                                8,
                                3,
                                26,
                                17,
                                32,
                                111,
                                110,
                                101,
                                111,
                                102,
                                32,
                                99,
                                111,
                                109,
                                109,
                                101,
                                110,
                                116,
                                115,
                                32,
                                10,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                8,
                                0,
                                1,
                                18,
                                3,
                                4,
                                8,
                                18,
                                10,
                                36,
                                10,
                                4,
                                4,
                                1,
                                2,
                                0,
                                18,
                                3,
                                6,
                                4,
                                20,
                                26,
                                23,
                                32,
                                102,
                                105,
                                101,
                                108,
                                100,
                                32,
                                111,
                                110,
                                101,
                                111,
                                102,
                                32,
                                99,
                                111,
                                109,
                                109,
                                101,
                                110,
                                116,
                                115,
                                32,
                                10,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                0,
                                5,
                                18,
                                3,
                                6,
                                4,
                                10,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                0,
                                1,
                                18,
                                3,
                                6,
                                11,
                                15,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                0,
                                3,
                                18,
                                3,
                                6,
                                18,
                                19,
                                10,
                                11,
                                10,
                                4,
                                4,
                                1,
                                2,
                                1,
                                18,
                                3,
                                7,
                                4,
                                31,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                1,
                                6,
                                18,
                                3,
                                7,
                                4,
                                14,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                1,
                                1,
                                18,
                                3,
                                7,
                                15,
                                26,
                                10,
                                12,
                                10,
                                5,
                                4,
                                1,
                                2,
                                1,
                                3,
                                18,
                                3,
                                7,
                                29,
                                30,
                            ],
                        ],
                    },
                },
            ),
        },
        cached_size: CachedSize {
            size: 0,
        },
    },
}